export const RECIPES_URL='http://localhost:3001/recipe'
export const INGREDIENTS_URL= 'http://localhost:3001/ingredients'
export const RECIPES_DETAIL_URL= 'http://localhost:3001/recipe/details/'
export const RECIPES_SEARCH_URL = 'http://localhost:3001/recipe/search/'
export const UNIT = 'http://localhost:3001/unit'
export const RECIPES_BY_INGREDIENTS = 'http://localhost:3001/recipe/filterByIngredient/'
export const REGISTER = 'http://localhost:3001/user'