// export const RECIPES_URL='https://recetapp-back.herokuapp.com/recipe'
// export const INGREDIENTS_URL= 'https://recetapp-back.herokuapp.com/ingredients'
// export const CATEGORY_URL= 'https://recetapp-back.herokuapp.com/category'
// export const RECIPES_DETAIL_URL= 'https://recetapp-back.herokuapp.com/recipe/details/'
// export const RECIPES_SEARCH_URL = 'https://recetapp-back.herokuapp.com/recipe/search/'
// export const REGISTER = 'https://recetapp-back.herokuapp.com/user'
// export const UNIT_URL = 'https://recetapp-back.herokuapp.com/unit'
// export const RECIPES_BY_INGREDIENTS_URL = 'https://recetapp-back.herokuapp.com/recipe/filterByIngredient/'
// export const RECIPES_BY_CATEGORY_URL ='https://recetapp-back.herokuapp.com/recipe/filterByCategory/'
// export const RECIPES_BY_DIFFICULTY_URL ='https://recetapp-back.herokuapp.com/recipe/filterByDifficulty/'

//Rutas para arreglar

export const RECIPES_URL='http://localhost:3001/recipe'
export const INGREDIENTS_URL= 'http://localhost:3001/ingredients'
export const CATEGORY_URL= 'http://localhost:3001/category'
export const RECIPES_DETAIL_URL= 'http://localhost:3001/recipe/details/'
export const RECIPES_SEARCH_URL = 'http://localhost:3001/recipe/search/'
export const REGISTER = 'http://localhost:3001/user/register'
export const UNIT_URL = 'http://localhost:3001/unit'
export const RECIPES_BY_INGREDIENTS_URL = 'http://localhost:3001/recipe/filterByIngredient/'
export const RECIPES_BY_CATEGORY_URL ='http://localhost:3001/recipe/filterByCategory/'
export const RECIPES_BY_DIFFICULTY_URL ='http://localhost:3001/recipe/filterByDifficulty/'
export const LOGIN = 'http://localhost:3001/user/login'
export const CALENDAR_URL = 'http://localhost:3001/calendar'
